import React, { ReactNode } from "react";
import {
  LaptopOutlined,
  NotificationOutlined,
  UserOutlined,
} from "@ant-design/icons";
import type { MenuProps } from "antd";
import { Breadcrumb, Layout as Antdlayout, Menu, Dropdown, Space } from "antd";
import styles from "./index.module.css";
import { useRouter } from "next/router";
import { DownOutlined } from "@ant-design/icons";
import Head from "next/head";

const { Header, Content, Sider } = Antdlayout;

const items1: MenuProps["items"] = ["1", "2", "3"].map((key) => ({
  key,
  label: `nav ${key}`,
}));

const items2: MenuProps["items"] = [
  UserOutlined,
  LaptopOutlined,
  NotificationOutlined,
].map((icon, index) => {
  const key = String(index + 1);

  return {
    key: `sub${key}`,
    icon: React.createElement(icon),
    label: `subnav ${key}`,

    children: new Array(4).fill(null).map((_, j) => {
      const subKey = index * 4 + j + 1;
      return {
        key: subKey,
        label: `option${subKey}`,
      };
    }),
  };
});

const ITEMS = [
  {
    key: "dashboard",
    label: "Dashboard",
  },
  {
    key: "glossary",
    label: "Glossary",
  },
  {
    key: "selflearning",
    label: "Self-learning Hub",
  },
  {
    key: "mscit",
    label: "Learning in MSC IT+",
  },

  {
    key: "englishsupport",
    label: "English Support",
  },
  {
    key: "postgraduatesupport",
    label: "Postgraduate-level Support",
  },
  {
    key: "usermgmt",
    label: "User Management",
  },
  {
    key: "glossarymgmt",
    label: "Glossary Management",
  },
  {
    key: "course",
    label: "MSc IT+ Management",
    children: [
      { key: "/course", label: "Course" },
      { key: "/course/feedback", label: "Course Feedback" },
    ],
  },
  {
    key: "selflearningmgmt",
    label: "Self-learning Management",

    children: [{ key: "/selflearningmgmt", label: "Video Management" }],
  },
];

const onClick: MenuProps["onClick"] = ({ key }) => {
  message.info(`Click on item ${key}`);
};

const USER_ITEMS: MenuProps["items"] = [
  {
    label: "Message",
    key: "message",
  },
  {
    label: "Log out",
    key: "login",
  },
];

export function Layout({ children }: { children: ReactNode }) {
  const router = useRouter();
  const handleMenuClick: MenuProps["onClick"] = ({ key }) => {
    router.push(key);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Antdlayout>
          <Header className={styles.header}>
            ITHunt
            <span className={styles.user}>
              <Dropdown menu={{ items: USER_ITEMS, onClick }}>
                <a onClick={(e) => e.preventDefault()}>
                  <Space>
                    User
                    <DownOutlined />
                  </Space>
                </a>
              </Dropdown>
            </span>
          </Header>
          <Antdlayout className={styles.sectionInner}>
            <Sider width={200}>
              <Menu
                mode="inline"
                defaultSelectedKeys={["/dashboard"]}
                defaultOpenKeys={["dashboard"]}
                style={{ height: "100%", borderRight: 0 }}
                items={ITEMS}
                onClick={handleMenuClick}
              />
            </Sider>
            <Antdlayout className={styles.sectionContent}>
              <Content className={styles.content}>{children}</Content>
            </Antdlayout>
          </Antdlayout>
        </Antdlayout>
      </main>
    </>
  );
}
