import React, { ReactNode } from "react";
import type { MenuProps } from "antd";
import { Layout as Antdlayout, Menu, Dropdown, Space, message } from "antd";
import styles from "./index.module.css";
import { useRouter } from "next/router";
import { DownOutlined } from "@ant-design/icons";
import Head from "next/head";
import { UserButton } from "@clerk/nextjs";

const { Header, Content, Sider } = Antdlayout;

const ITEMS = [
  {
    key: "dashboard",
    label: "Dashboard",
  },
  {
    key: "glossary",
    label: "Glossary",

    children: [
      { key: "/glossary", label: "Glossary" },
      { key: "/glossary/list", label: "Glossary List" },
    ],
  },
  {
    key: "course",
    label: "Learning in MSC IT+",

    children: [
      { key: "/course", label: "Course" },
      { key: "/course/list", label: "Course List" },
      { key: "/course/feedback", label: "Course Feedback" },
    ],
  },
  {
    key: "selflearning",
    label: "Self-learning Hub",

    children: [
      { key: "/selflearning", label: "Course" },
      { key: "/selflearning/quiz", label: "Quiz" },
      { key: "/selflearning/courselist", label: "Course List" },
      { key: "/selflearning/questionlist", label: "Questions List" },
    ],
  },

  {
    key: "englishsupport",
    label: "English Support",
  },
  {
    key: "postgraduatesupport",
    label: "Postgraduate-level Support",
  },
  {
    key: "users",
    label: "Users",
  },
];

const USER_ITEMS: MenuProps["items"] = [
  {
    label: "Notification",
    key: "/dashboard/notification",
  },
  {
    label: "Log out",
    key: "login",
  },
];

export function Layout({ children }: { children: ReactNode }) {
  const router = useRouter();
  const handleMenuClick: MenuProps["onClick"] = ({ key }) => {
    router.push(key);
  };

  const onClick: MenuProps["onClick"] = ({ key }) => {
    message.info(`Click on item ${key}`);
    router.push(key);
  };

  const activeMenu = router.pathname;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Antdlayout>
          <Header className={styles.header}>
            ITHunt
            <span className={styles.user}>
              <UserButton />
              <Dropdown menu={{ items: USER_ITEMS, onClick }}>
                <a onClick={(e) => e.preventDefault()}>
                  <Space>
                    User
                    <DownOutlined />
                  </Space>
                </a>
              </Dropdown>
            </span>
          </Header>
          <Antdlayout className={styles.sectionInner}>
            <Sider width={200}>
              <Menu
                mode="inline"
                defaultSelectedKeys={["/dashboard"]}
                defaultOpenKeys={["dashboard"]}
                selectedKeys={[activeMenu]}
                style={{ height: "100%", borderRight: 0 }}
                items={ITEMS}
                onClick={handleMenuClick}
              />
            </Sider>
            <Antdlayout className={styles.sectionContent}>
              <Content className={styles.content}>{children}</Content>
            </Antdlayout>
          </Antdlayout>
        </Antdlayout>
      </main>
    </>
  );
}
