server:
    port: 9090

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ithunt_system
        username: root
        password: 12345678
        driver-class-name: com.mysql.cj.jdbc.Driver